services:
  postgres:
    image: postgres:17.2
    container_name: spring-security-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
